export const ORGANIZATION_REPOSITORY = Symbol('ORGANIZATION_REPOSITORY');
export const ORGANIZATION_MEMBER_REPOSITORY = Symbol(
  'ORGANIZATION_MEMBER_REPOSITORY',
);
export const ORGANIZATION_INVITE_REPOSITORY = Symbol(
  'ORGANIZATION_INVITE_REPOSITORY',
);
